// Audit logs: discounts, voids, and Z-reports (FR-006, FR-030, FR-046)

import { relations, sql } from "drizzle-orm";
import {
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";
import { branch } from "./branch";
import { order } from "./order";
import { organization } from "./organization";
import { user } from "./user";
import { orderItem } from "./order-item";

/**
 * Discount type enum — percentage-based or fixed-amount discount.
 */
export const discountTypeEnum = pgEnum("discount_type", [
  "percentage",
  "fixed",
]);

/**
 * Void scope enum — voiding a single item vs. an entire order.
 */
export const voidTypeEnum = pgEnum("void_type", ["item", "order"]);

/**
 * Discount log — immutable audit record of every discount applied.
 *
 * Every discount requires manager PIN approval (FR-030).
 * approver_id is nullable for future system-applied discounts (loyalty, etc.).
 */
export const discountLog = pgTable(
  "discount_log",
  {
    id: text()
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    organizationId: text()
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    branchId: text().references(() => branch.id, { onDelete: "set null" }),
    orderId: text()
      .notNull()
      .references(() => order.id, { onDelete: "cascade" }),
    requesterId: text()
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    approverId: text().references(() => user.id, { onDelete: "set null" }),
    discountType: discountTypeEnum().notNull(),
    discountValue: numeric({ precision: 10, scale: 2 }).notNull(),
    discountAmount: numeric({ precision: 10, scale: 2 }).notNull(),
    reason: text(),
    createdAt: timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("discount_log_org_id_idx").on(table.organizationId),
    index("discount_log_order_id_idx").on(table.orderId),
    index("discount_log_requester_id_idx").on(table.requesterId),
    index("discount_log_created_at_idx").on(table.createdAt),
  ],
);

export type DiscountLog = typeof discountLog.$inferSelect;
export type NewDiscountLog = typeof discountLog.$inferInsert;

/**
 * Void log — immutable audit record of every item or order void.
 *
 * order_item_id nullable: null = full order void, set = single item void.
 * approver_id nullable: set when manager PIN is required and provided.
 */
export const voidLog = pgTable(
  "void_log",
  {
    id: text()
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    organizationId: text()
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    branchId: text().references(() => branch.id, { onDelete: "set null" }),
    orderId: text()
      .notNull()
      .references(() => order.id, { onDelete: "cascade" }),
    orderItemId: text().references(() => orderItem.id, {
      onDelete: "set null",
    }),
    requesterId: text()
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    approverId: text().references(() => user.id, { onDelete: "set null" }),
    voidType: voidTypeEnum().notNull(),
    reason: text(),
    createdAt: timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("void_log_org_id_idx").on(table.organizationId),
    index("void_log_order_id_idx").on(table.orderId),
    index("void_log_requester_id_idx").on(table.requesterId),
    index("void_log_created_at_idx").on(table.createdAt),
  ],
);

export type VoidLog = typeof voidLog.$inferSelect;
export type NewVoidLog = typeof voidLog.$inferInsert;

/**
 * Top item entry in Z-report snapshot.
 */
export interface ZReportTopItem {
  menuItemId: string | null;
  name: string;
  count: number;
  revenue: string;
}

/**
 * Z-report — point-in-time end-of-day financial snapshot (FR-046).
 *
 * Design: Immutable after generation. Covers a configurable period
 * (period_start → period_end). Generated by a manager, read-only thereafter.
 * top_items stored as JSONB for flexible querying and receipt rendering.
 */
export const zReport = pgTable(
  "z_report",
  {
    id: text()
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    organizationId: text()
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    branchId: text()
      .notNull()
      .references(() => branch.id, { onDelete: "cascade" }),
    generatedBy: text()
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    periodStart: timestamp({ withTimezone: true, mode: "date" }).notNull(),
    periodEnd: timestamp({ withTimezone: true, mode: "date" }).notNull(),
    grossSales: numeric({ precision: 12, scale: 2 }).notNull(),
    netSales: numeric({ precision: 12, scale: 2 }).notNull(),
    vatAmount: numeric({ precision: 12, scale: 2 }).notNull(),
    discountTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    voidTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    tipTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    cashTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    promptpayTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    cardTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    otherTotal: numeric({ precision: 12, scale: 2 }).notNull(),
    orderCount: integer().notNull(),
    dineInCount: integer().notNull(),
    takeawayCount: integer().notNull(),
    deliveryCount: integer().notNull(),
    topItems: jsonb().$type<ZReportTopItem[]>().notNull(),
    createdAt: timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("z_report_org_id_idx").on(table.organizationId),
    index("z_report_branch_id_idx").on(table.branchId),
    index("z_report_period_start_idx").on(table.periodStart),
    index("z_report_generated_by_idx").on(table.generatedBy),
  ],
);

export type ZReport = typeof zReport.$inferSelect;
export type NewZReport = typeof zReport.$inferInsert;

export const discountLogRelations = relations(discountLog, ({ one }) => ({
  organization: one(organization, {
    fields: [discountLog.organizationId],
    references: [organization.id],
  }),
  branch: one(branch, {
    fields: [discountLog.branchId],
    references: [branch.id],
  }),
  order: one(order, {
    fields: [discountLog.orderId],
    references: [order.id],
  }),
  requester: one(user, {
    fields: [discountLog.requesterId],
    references: [user.id],
  }),
  approver: one(user, {
    fields: [discountLog.approverId],
    references: [user.id],
  }),
}));

export const voidLogRelations = relations(voidLog, ({ one }) => ({
  organization: one(organization, {
    fields: [voidLog.organizationId],
    references: [organization.id],
  }),
  branch: one(branch, {
    fields: [voidLog.branchId],
    references: [branch.id],
  }),
  order: one(order, {
    fields: [voidLog.orderId],
    references: [order.id],
  }),
  orderItem: one(orderItem, {
    fields: [voidLog.orderItemId],
    references: [orderItem.id],
  }),
  requester: one(user, {
    fields: [voidLog.requesterId],
    references: [user.id],
  }),
  approver: one(user, {
    fields: [voidLog.approverId],
    references: [user.id],
  }),
}));

export const zReportRelations = relations(zReport, ({ one }) => ({
  organization: one(organization, {
    fields: [zReport.organizationId],
    references: [organization.id],
  }),
  branch: one(branch, {
    fields: [zReport.branchId],
    references: [branch.id],
  }),
  generatedByUser: one(user, {
    fields: [zReport.generatedBy],
    references: [user.id],
  }),
}));
